import type { Metadata } from "next";
import { Roboto, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "./component/navbar/navbar";
import AuthProvider from "./AuthProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = getServerSession(authOptions);

  return (
    <AuthProvider session={session}>
      <html lang="en">
        <body className={roboto.className}>
          <NavBar />
          <div style={{ height: "70px" }}></div>
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
